<!-- This code was generated by Builder.io -->
<template>
  <article class="related-item-card">
    <!-- <button @click="handleClick"> -->
    <img :src="item.image" :alt="item.title" class="related-item-card__image" />
    <!-- </button> -->
    <div class="related-item-card__content">
      <h3 class="related-item-card__title">{{ item.title }}</h3>
      <p class="related-item-card__description">{{ item.description }}</p>
      <p class="related-item-card__price">${{ item.price.toFixed(2) }}</p>
      <p class="related-item-card__bought">{{ item.bought }} Bought</p>
    </div>
  </article>
</template>

<script setup lang="ts">
import { defineComponent, PropType } from 'vue'
const props = defineProps<{ item: Item }>()


interface Item {
  image: string
  title: string
  description: string
  price: number
  bought: number
}

</script>

<style scoped>
.related-item-card {
  border-radius: 24px;
  background-color: #fafaf5;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  color: #000;
  font:
    600 20px/1.3 Inter,
    sans-serif;
  border: 2px solid #e6e6e6;
}

.related-item-card__image {
  aspect-ratio: 0.98;
  object-fit: contain;
  object-position: center;
  width: 100%;
}

.related-item-card__content {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 18px 21px 17px;
}

.related-item-card__title {
  font-size: 20px;
  font-weight: 600;
  margin: 0;
}

.related-item-card__description {
  font-weight: 400;
  margin: 10px 0 0;
}

.related-item-card__price {
  color: #f00;
  font-size: 16px;
  margin: 85px 0 0;
}

.related-item-card__bought {
  font-size: 16px;
  font-weight: 400;
  margin: 0;
}

@media (max-width: 991px) {
  .related-item-card__content {
    padding: 18px 10px 17px;
  }

  .related-item-card__price {
    margin-top: 40px;
  }
}
</style>
