client_id = "4442f350454cb717f95350a478bdb91f"
name = "Product Recommendation"
handle = "product-recommendation-2212"
application_url = "https://localhost"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales, read_orders, read_products, read_themes"

[auth]
redirect_urls = [
    "https://localhost/authenticate"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled","shop/update", "products/create", "products/update", "products/delete"]
uri = "https://a50e-118-71-116-176.ngrok-free.app/webhook"

[pos]
embedded = false

[app_preferences]
url = "https://www.app.example.com/preferences"
