<!-- This code was generated by Builder.io -->
<template lang="pug">
  section.related-items
    .title More thing you find
    Text
    .grid
      Item(v-for="item in items" :key="item.image" :item="item")
</template>

<script setup lang="ts">
import { reactive, Text} from 'vue'
import Item from './Item/Item.vue'

const items = reactive([
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/a6e1f446bd7f66159e8aaf33b0d3172227190a9aea7973ae07aa08075f8d2205?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'ijjijij',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/9ca8cad4b0273da6a4de79957d1b7811eb84ef1aba72b9f89e0c295a80c1b6d0?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'Order summary',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/9ca8cad4b0273da6a4de79957d1b7811eb84ef1aba72b9f89e0c295a80c1b6d0?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'Order summary',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/95166c48b249a9fa301f00206c870880981fa4d76ceafec3f37e71119b57b571?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'Order summary',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/95166c48b249a9fa301f00206c870880981fa4d76ceafec3f37e71119b57b571?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'Order summary',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/95166c48b249a9fa301f00206c870880981fa4d76ceafec3f37e71119b57b571?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'Order summary',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/95166c48b249a9fa301f00206c870880981fa4d76ceafec3f37e71119b57b571?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'Order summary',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/95166c48b249a9fa301f00206c870880981fa4d76ceafec3f37e71119b57b571?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'Order summary',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
  {
    image: 'https://cdn.builder.io/api/v1/image/assets/TEMP/95166c48b249a9fa301f00206c870880981fa4d76ceafec3f37e71119b57b571?placeholderIfAbsent=true&apiKey=3786680e13174bd88bc8c99173311cdc',
    title: 'Order summary',
    description: 'A super power tomatoes',
    price: 33.43,
    bought: 455,
  },
])
</script>

<style scoped lang="scss">
.related-items {
  background-color: #ffffff;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 50px 80px 79px;
  .title {
    color: #000;
    letter-spacing: 0.48px;
    font-weight: 680;
    text-align: center;
    font: 600 58px/1.2 Newsreader, sans-serif;
    margin-bottom: 69px;
  }
  .grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
    width: 100%;
    max-width: 1249px;
  }
}


@media (max-width: 991px) {
  .related-items {
    padding: 40px 20px;
  }

  .related-items__title {
    font-size: 60px;
    margin-bottom: 40px;
  }

  .related-items__grid {
    grid-template-columns: 1fr;
  }
}
</style>
